[[tasks]]
time = "2025-01-03"
task_id = "12345"
title = "title"
commit = "666"
status = "In Progress"
active = true

[[tasks]]
time = "2025-01-04"
task_id = "67890"
title = "title"
commit = "8888"
status = "Done"
active = false

[[tasks]]
time = "2026-05-10"
task_id = "arVnAZSa31"
title = "我的新任务"
commit = "deadbeef"
status = "In Progress"
active = true
